# Generated by Django 5.1.7 on 2025-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a', models.CharField(max_length=100)),
                ('value_b', models.FloatField(max_length=100)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
